# Copyright (c) IFM Lab. All rights reserved.

name: vqa
channels:
  - pytorch
  - defaults
  - conda-forge  
  # - mkdocs-material
dependencies:
  - python=3.10  
  - pip  
  - ninja
  - cudatoolkit=11.3
  - pytorch==1.12.0
  - torchaudio==0.12.0
  - torchvision==0.13.0
  - tensorboardx==2.6.2.2
  - pip:
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.4
      - transformers==4.46.3
      - numpy==1.26.4
      - pandas==2.2.3
      - sympy==1.13.3
      - einops==0.8.1
      - sentencepiece==0.2.0
      - h5py==3.12.1
      - fvcore==0.1.5
      - gdown==5.2.0
      - scipy==1.14.1
      - decord==0.6.0
      - mkdocs-material
      - neoteroi-mkdocs
      - mkdocs-macros-plugin
      - mkdocs-jupyter
      - mkdocstrings
      - mkdocs-rss-plugin
      - mkdocs-exclude
      - mkdocstrings[python]
      